CREATE TABLE IF NOT EXISTS users(
    user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email varchar(255) CHARACTER SET utf8mb4 UNIQUE NOT NULL,
    passwordhash char(60) NOT NULL,
    isadmin BOOL DEFAULT FALSE,
    lastupdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    timecreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);